services:
  - type: web
    name: smartexpenseai
    env: go
    region: singapore
    buildCommand: |
      mkdir -p bin &&
      cd cmd &&
      go mod tidy &&
      go build -o ../bin/server main.go
    startCommand: ./bin/server
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /setup-webhook
